config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: "homes#index"


  get :admin, :to => 'admin/homes#index'

  devise_for :users, controllers: {registrations: 'registrations'}

  namespace :admin do
    resources :homes
    resources :recipes
    
  end

  resources :user_details
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_one :user
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
     validates :description, :ingredient, :direction, :specific, :difficulty, :title, :presence => true

     def recipes
     	self.all
     end

     def recipe
     	self.find params[:id]
     end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         has_many :recipes


    User_types = ["user", "super_user", "admin", "super-admin"]




    def is_admin?
    	 self.user_type == 3
    end

    def is_manager?
    	self.user_type == 2
    end

    def is_publisher?
    	self.user_type == 1
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
	before_filter :have_permission?
	def index
		@users = User.all
		@recipes = Recipe.all
	end

	private

	def have_permission?
		unless current_user.is_admin?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path # halts request cycle
    end
	end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
	def index
		@recipes = Recipe.all

	end

	def show
		@recipe = Recipe.find params[:id]
	end

	def new
		@recipe = Recipe.new
	end

	def edit
	  @recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
	    @recipe.update!(recipe_params)
	    redirect_to @recipe
	end

	def create
		@recipe = Recipe.new recipe_params
		if @recipe.save
	      redirect_to admin_recipe_path(@recipe)
	      flash[:success] = "Reteta creata cu succes!"
	    else
	      # This line overrides the default rendering behavior, which
	      # would have been to render the "create" view.
	      redirect_to new_admin_recipe_path
	      flash[:error] = "Completeaza toate campurile!"
	    end
	end

	def destroy
		Recipe.find(params[:id]).destroy
     	redirect_to admin_recipes_path
	end

	private

		def recipe_params
		    params.require(:recipe).permit(:title, :ingredient, :direction, :type, :specific, :difficulty, :description, :user_id, :image)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_type, :last_name, :first_name, :email, :password, :password_confirmation) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_type) }
  end

  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	
	def index
		
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController

	def index
		@user_detail = UserDetail.find params[:id]
	end
	def create
		@user_detail = UserDetail.new user_detail_params
		if @user_detail.save
	      redirect_to root_path
	    else
	      # This line overrides the default rendering behavior, which
	      # would have been to render the "create" view.
	      render "new"
	    end
	end

	private

		def user_detail_params
		    params.require(:user_detail).permit(:first_name, :last_name, :age, :description, :user_id)
		end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
    before_filter :configure_permitted_parameters

  protected

  # my custom fields are :name, :heard_how
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name,
        :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name,
        :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/index.html.erb
<h1>Lista tuturor reterelor</h1>
<div class="row">
<%= render partial: "admin/recipes/recipe"%>
</div>

app/views/admin/recipes/_recipe.html.erb
<% @recipes.each do |recipe| %>
	<div class="col-md-12">
		<%= link_to admin_recipe_path(recipe) do %>
			<div class="recipe-element-container">
				<% if recipe.image.present? %>
					<%= image_tag recipe.image.url(:thumb) %>
				<% end %>
				<%= recipe.title %>
				
			</div>
		<% end %>
		<%= link_to "Delete", admin_recipe_path(recipe), :confirm => "Are you sure?", :method => :delete %>
	</div>

<% end %>
<%= link_to "Reteta noua", new_admin_recipe_path %>

app/views/admin/recipes/edit.html.erb
<div class="row">
	<div class="col-md-12">
		<%= form_for @recipe, url: admin_recipes_path do |f| %>
		<div class="form-horizontal">
			<div class="form-group">
				<div class="col-md-12">
					<%= f.label :title%>
					<%= f.text_field :title, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-12">
					<%= f.label :description %>
					<%= f.cktext_area  :description, :ckeditor => {:toolbar => 'mini'}, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-12">
					<%= f.label :ingredient %>
					<%= f.cktext_area  :ingredient,  :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'}, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-12">
					<%= f.label :direction %>
					<%= f.cktext_area  :direction, :ckeditor => {:toolbar => 'mini'}, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-12">
					<%= f.label :type %>
					<%= f.text_field :type, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-12">
					<%= f.label :specific %>
					<%= f.text_field :specific, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-12">
					<%= f.label :difficulty %>
					<%= f.text_field :difficulty, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-12">
					<%= f.file_field :image, as: :file %>
				</div>
			</div>
				<%= f.submit "Submit", class: "btn btn-default pull-right" %>
		</div>
		<% end %>
	</div>
</div>

app/views/admin/recipes/index.html.erb
<h1>Lista tuturor reterelor</h1>
<div class="row">
<%= render partial: "admin/recipes/recipe"%>
</div>

app/views/admin/recipes/new.html.erb
<div class="row">
	<div class="col-md-12">
		<%= form_for @recipe, url: admin_recipes_path do |f| %>
			<div class="row">
				<div class="col-md-6">
					<%= f.label :image%>
					
						<%= f.file_field :image, as: :file, id: "pictureInput", class: "hidden" %>
						<div class="image-wrapper">
							<div class="upload-text"><i class="fa fa-upload"></i>INCARCA IMAGINEA RETETEI TALE</div>
					</div>

					<div id="target">
						
					</div>
				</div>

				<div class="col-md-6">
					<%= f.label :title%>
					<%= f.text_field :title, class: "form-control" %>
					<%= f.label :description %>
					<%= f.text_field  :description, class: "form-control" %>
				
					<div class="row">
						<div class="col-md-12">
							<%= f.label :ingredient %>
							<%= f.text_field  :ingredient, class: "form-control" %>
						</div>
						<div class="col-md-12">
							<%= f.label :direction %>
							<%= f.text_field  :direction, class: "form-control" %>
						</div>
					</div>
				
					<div class="row">
						<div class="col-md-12">
							<%= f.label :type %>
							<%= f.text_field :type, class: "form-control" %>
						</div>
						<div class="col-md-12">
							<%= f.label :specific %>
							<%= f.text_field :specific, class: "form-control" %>
						</div>
						<div class="col-md-12">
							<%= f.label :difficulty %>
							<%= f.text_field :difficulty, class: "form-control" %>
						</div>
						<div class="col-md-12">
							<%= f.submit "Adauga noua reteta >>", 'data-disable-with' => "Se proceseaza...", class: "btn btn-default pull-right btn-recipes" %>
						</div>				
					</div>
				</div>
			</div>		
			
		<% end %>
	</div>
</div>

app/views/admin/recipes/show.html.erb
<%= @recipe.title%><br><br>
<%= @recipe.description.html_safe%>
<%= link_to "Edit recipe", edit_admin_recipe_path%>

app/views/admin/users/index.html.erb
<%= @users%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AplicatieReteta</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= params[:controller].to_s.split('/').first%>-body'>


	<div class="container">
		<% flash.each do |name, msg| -%>
	      <%= content_tag :div, msg, class: "flash message-#{name}" %>
	    <% end -%>
		<div class="header">
			<div class="row">
				<div class="col-xs-6">
					<div class="main-title">
						<h1>Reteta mea</h1>
					</div>
				</div>
				<div class="col-xs-2">
					<% if user_signed_in? %>
						<% if current_user.is_admin? %>
							<%= link_to "Admin panel", admin_homes_path %>
						<% end %>
					<% end %>
				</div>
				<div class="col-xs-4">
					<% if user_signed_in? %>
						<%= current_user.first_name %><%= current_user.last_name%>
					<% else %>
						<%= link_to "Sign in", new_user_session_path %>
						<%= link_to "Sign up", new_user_registration_path %>
					<% end %>
				</div>
			</div>
		</div>
		<%= yield %>
	</div>
		<div class="footer">
			<div class="container">
				<div class="row">
					<div class="col-xs-4">
						news and others Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
						cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
						proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					</div>
					<div class="col-xs-4">
						search and latest recepies Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
						cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
						proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					</div>
					<div class="col-xs-4">
						info about as Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
						cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
						proident, sunt in culpa qui officia deserunt mollit anim id est laborum.s
					</div>
				</div>
		</div>
		</div>
</body>
</html>